apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  annotations:
    auto-reload.raynigon.com/configMap: "default/demo-config"
spec:
  containers:
  - name: bash
    image: bash
    args: ["sleep", "infinity"]